// 浏览器全局版趣味关键词库
window.idKeywords = {
    '奶': { tag: '奶妈人设', meme: 5 },
    '爷': { tag: '大爷气质', meme: 8 },
    '骚': { tag: '操作骚气', operation: 5 },
    '狗': { tag: '反向渣男', rapport: -5 },
    '酱': { tag: '甜蜜气息', rapport: 10 },
    '王': { tag: '排位之王', carry: 10 },
    '帝': { tag: '峡谷之帝', carry: 8 },
    '鬼': { tag: '幽灵刺客', operation: 8, meme: 5 },
    '浪': { tag: '浪里白条', meme: 10 },
    '心': { tag: '温暖之心', rapport: 12 },
    '兮': { tag: '古风小生', rapport: 8 },
    '甜': { tag: '甜妹能量', rapport: 12 },
    '糖': { tag: '峡谷小甜饼', rapport: 10 },
    '星': { tag: '星光选手', awareness: 6 },
    '月': { tag: '月下清醒派', awareness: 8 },
    '明哲': { tag: '明哲保身但能赢', awareness: 8, mentality: 8 },
    '风': { tag: '风一样支援', operation: 5 },
    '云': { tag: '云端漫游者', meme: 6 },
    '梦': { tag: '做梦都在上分', carry: 7 },
    '鱼': { tag: '峡谷摸鱼王', meme: 8 },
    '猫': { tag: '猫系玩家', rapport: 8 },
    '兔': { tag: '兔兔冲分机', operation: 5 },
    '鹿': { tag: '温柔小鹿', rapport: 10 },
    '茶': { tag: '奶茶续命党', meme: 6 },
    '困': { tag: '困困也要赢', mentality: 6 },
    '睡': { tag: '梦游峡谷派', meme: 8 },
    '菜': { tag: '自嘲型高手', rapport: 6 },
    '神': { tag: '自封峡谷神', carry: 8 },
    '仙': { tag: '仙气走位', operation: 6 },
    '宝': { tag: '队内小宝贝', rapport: 12 },
    '崽': { tag: '可爱崽崽', rapport: 10 },
    '崽崽': { tag: '被保护位', rapport: 12 },
    '哥哥': { tag: '可靠哥哥', rapport: 8 },
    '姐姐': { tag: '靠谱姐姐', rapport: 8 },
    '小': { tag: '小小一只很能打', operation: 4 },
    '大': { tag: '大场面选手', carry: 6 },
    '猛': { tag: '峡谷猛将', operation: 8 },
    '酷': { tag: '高冷酷盖', mentality: 6 },
    '乖': { tag: '乖巧上分人', rapport: 9 },
    '野': { tag: '野区雷达', awareness: 8 },
    '中': { tag: '中路节奏点', awareness: 6 },
    '射': { tag: '后排输出位', carry: 7 },
    '辅': { tag: '团队守护者', rapport: 10 },
    '爱': { tag: '爱意满格', rapport: 12 },
    '快乐': { tag: '快乐至上', meme: 10 },
    '上分': { tag: '上分执念', carry: 10 },
    '摆烂': { tag: '摆烂但可爱', meme: 12 },
    '躺赢': { tag: '躺赢玄学家', meme: 8 },
    '不想输': { tag: '胜负欲在线', carry: 9 },
    '别送': { tag: '队友情绪雷达', awareness: 6 },
    '别抢': { tag: 'Buff 守护者', mentality: 4 },
    '带飞': { tag: '带飞预备役', carry: 10 },
    '救命': { tag: '求救信号满级', rapport: 6 },
    '救救': { tag: '呼叫支援专家', rapport: 7 },
    '冲': { tag: '开团冲锋手', operation: 7 },
    '稳住': { tag: '稳住我们能赢', mentality: 10 },
    '别急': { tag: '峡谷定心丸', mentality: 10 },
    '别慌': { tag: '逆风稳局者', mentality: 10 },
    '开麦': { tag: '语音指挥官', awareness: 8 },
    '闭麦': { tag: '沉默实力派', mentality: 7 },
    '认真': { tag: '认真上分人', carry: 8 },
    '随缘': { tag: '随缘快乐派', meme: 8 },
    '佛系': { tag: '佛系保心态', mentality: 9 },
    '发育': { tag: '发育等我 C', awareness: 7 },
    '守家': { tag: '守家专家', mentality: 8 },
    '偷塔': { tag: '偷塔小天才', awareness: 9 },
    '五杀': { tag: '五杀幻想家', carry: 8 },
    '瑶': { tag: '峡谷挂件美学', rapport: 10 },
    '香香': { tag: '大小姐火力', operation: 8 },
    '李白': { tag: '诗酒剑仙梦', operation: 8 },
    '韩信': { tag: '野区跑酷王', operation: 10 },
    '貂蝉': { tag: '花间舞步', operation: 8 },
    '鲁班': { tag: '小短腿大火力', carry: 7 },
    '孙膑': { tag: '时间管理大师', awareness: 9 },
    '大乔': { tag: '电梯调度员', awareness: 10 }
};
